Feature/syal 181
AVISPL/dal-codecs-singlecodecs-polycom-realpresence-groupseries pull request #5
Opened 2021-04-01 13:23 UTC by MaksimR-AVISPL

2021-04-01 16:41 UTC, ShervinM-AVISPL requested changes

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if(value.contains("only supported")) {
I'm not too familiar with how these APIs work, but should we return false, if the value contains "only supported"? I guess I don't understand what "only supported" means, hence I just wanted to make sure this logic is correct.

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if(cameraPosition.length > 0) {
Since getCameraPosition() method instantiates the Float array (Float[] cameraPositionArray = new Float[3];), its size will always be greater than 0. So, there is no point for this check.

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if(value == null) {
Why not use StringUtils.isNullOrEmpty(value, true)?
I don't see a point in continuing if value is empty.

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if(volume != null) {
Why not use StringUtils.isNullOrEmpty(volume, true)?
I don't see a point in continuing if value is empty.

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +            if(volumeLevel != null) {
what if volume level is empty? can Float.valueOf(volumeLevel) that is being performed on next line handle an empty string?

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        addStatisticsProperty(statistics, "SystemStatus#IPNetwork", StringUtils.getDataBetween(status, "ipnetwork ", LINE_BREAKER));
Please make sure StringUtils.getDataBetween() method handles null or empty values properly.

2021-04-01 16:41 UTC, ShervinM-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if (com.avispl.symphony.dal.util.StringUtils.isNullOrEmpty(value)) {
I see you use multiple versions of isNullOrEmpty() in this class (I see imported com.avispl.dal.communicator.polycom.groupseries.utils.StringUtils;), and now I see com.avispl.symphony.dal.util.StringUtils. Didn't we decide to unify them? I thought we were going to remove the groupSeries one...just wondering :)

2021-04-19 15:50 UTC, MaksimR-AVISPL commented on src/main/java/com/avispl/dal/communicator/polycom/groupseries/PolycomGroupSeries.java
> +        if(value.contains("only supported")) {
Well, basically, some properties are not supported for certain models, so the message like "this feature is only supported for eagle eye director 2" will be returned, so it's boiled down to "only supported", and then the property is skipped. Do you think it should be more explicit?

2021-04-19 17:01 UTC, ShervinM-AVISPL approved these changes
Approving, please address one last comment (about inline comment) and format whole file before you merge.

2021-04-19 17:31 UTC, merged